### ISSUE TITLE
Replace less with postcss

### ISSUE THREAD

**Issue by ckanitz** [luehrsenheinrich/wp-theme-boilerplate#23]

**Comment by ckanitz** [comment]
@Luehrsen integration via webpack or grunt?

**Comment by Luehrsen** [comment]
Integrate via grunt. 

Please adhere to the following folder structure.

- `build/css/src` All raw css files to be processed by postcss
- `dist/css/*.css` The final css files after processing, but before cssnano.
- `dist/css/*.min.css` The final css files after cssnano.

The style.css in the theme root folder does not hold styles anymore. 

We will want to move on to componetised CSS files. (e.g. footer.css, single.css, archive.css)
The only 'special' css file is the `base.css` file, as this file holds all styles needed to provide the base scaffolding for the page, the base typography and base styles for the header.

The intent is to only load the base.css in the header to provide a quick fist paint and load the rest of the css files in the footer or via javascript.
